//using System;
//using System.Collections.Generic;
//using System.Linq;
//using System.Web;
//using System.Web.Mvc;
//using JQxGrid.Models;
//using Trirand.Web.Mvc;
//using System.Web.UI.WebControls;

//namespace JQxGrid.Controllers.Grid
//{
//    public partial class GridController : Controller
//    {
//        // This is the default action for the View. Use it to setup your grid Model.
//        public ActionResult PivotMultipleAggregates()
//        {
//            // Get the model (setup) of the grid defined in the /Models folder.
//            var gridModel = new PivotJqGridModel();
//            var grid = gridModel.PivotGrid;

//            // Setting the DataUrl to an action (method) in the controller is required.
//            // This action will return the data needed by the grid           
//            grid.DataUrl = Url.Action("PivotMultipleAggregates_DataRequested");

//            SetUpGrid_PivotMultipleAggregates(grid);

//            // Pass the custmomized grid model to the View
//            return View(gridModel);
//        }

//        // This method is called when the grid requests data. You can choose any method to call
//        // by setting the JQGrid.DataUrl property
//        public JsonResult PivotMultipleAggregates_DataRequested()
//        {
//            // Get both the grid Model and the data Model
//            // The data model in our case is an autogenerated linq2sql database based on Northwind.
//            var gridModel = new PivotJqGridModel();
//            var northWindModel = new NorthwindDataContext();

//            IQueryable query = from p in northWindModel.Products
//                               join od in northWindModel.Order_Details on p.ProductID equals od.ProductID
//                               join cat in northWindModel.Categories on p.CategoryID equals cat.CategoryID
//                               join o in northWindModel.Orders on od.OrderID equals o.OrderID
//                               join c in northWindModel.Customers on o.CustomerID equals c.CustomerID
//                               where c.Country == "USA" || c.Country == "UK" || c.Country == "Germany"
//                               select new
//                               {
//                                   CategoryName = cat.CategoryName,
//                                   ProductName = p.ProductName,
//                                   Country = c.Country,
//                                   Price = od.Quantity * od.UnitPrice,
//                                   Quantity = od.Quantity
//                               };

//            SetUpGrid_PivotMultipleAggregates(gridModel.PivotGrid);
//            // return the result of the DataBind method, passing the datasource as a parameter
//            // jqGrid for ASP.NET MVC automatically takes care of paging, sorting, filtering/searching, etc
//            return gridModel.PivotGrid.DataBind(query);
//        }

//        public void SetUpGrid_PivotMultipleAggregates(JQGrid grid)
//        {
//            var pivot = grid.PivotSettings;
//            pivot.RowTotals = true;
//            pivot.ColTotals = true;
//            pivot.FrozenStaticCols = true;
//            pivot.GroupSummaryPosition = GroupSummaryPosition.Footer;
//            pivot.XDimension.Add(new PivotDimension { DataName = "CategoryName" });
//            pivot.XDimension.Add(new PivotDimension { DataName = "ProductName" });
//            pivot.YDimension.Add(new PivotDimension { DataName = "Country" });
//            pivot.Aggregates.Add(new PivotAggregate
//            {
//                Member = "Price",
//                Aggregator = PivotAggregator.Sum,
//                Width = 80,
//                Label = "Sum",
//                GroupSummaryType = GroupSummaryType.Sum,
//                Formatter = PivotFormatter.Number,
//                Align = Trirand.Web.Mvc.TextAlign.Right
//            });
//            pivot.Aggregates.Add(new PivotAggregate
//            {
//                Member = "Quantity",
//                Aggregator = PivotAggregator.Sum,
//                Width = 80,
//                Label = "Sum",
//                GroupSummaryType = GroupSummaryType.Sum,
//                Formatter = PivotFormatter.Number,
//                Align = Trirand.Web.Mvc.TextAlign.Right
//            });


//            grid.PagerSettings.PageSize = 10;
//            grid.Height = Unit.Pixel(300);
//            grid.Width = Unit.Pixel(800);

//        }
//    }
//}